### ISSUE TITLE
No way to set "force-frame-pointers=yes" when building Firecracker

### ISSUE THREAD

**Issue by theosib-amazon** [firecracker-microvm/firecracker#2816] opened 2021-12-10 21:14 UTC
To do system-wide profiling with Firecracker, I need frame pointers to be used by compiled code. That is, I need to set "force-frame-pointers=yes" in the rustflags for Firecracker. I need to do this, because I'm seeing orphaned function names when profiling for whom I cannot get call stacks.

The first thing I tried was to add the following to my `~/.cargo/config`.

```
[build]
rustflags = ["-C", "force-frame-pointers=yes"]
```

However, it appears that this aspect of my user environment isn't being copied into the docker container in which Firecracker is built.

I have also tried various ways of putting this into the Cargo.toml file, but I always get a warning that the manifest key I added isn't being used.

From what I can tell, there is no way to set "force-frame-pointers=yes" without some kind of deep dive into the docker container contents, but for something like a VM, profiling is important when there are potential performance bottlenecks.

**Comment by dianpopa** [comment] 2021-12-20 14:25
Hi @theosib-amazon ,

I will be taking a look at this issue. 
Can you please confirm that the way you are building Firecracker is `./tools/devtool build`?
Have you also tried going into the docker container with `./tools/devtool shell -p` and then simply run `cargo build` inside it?

**Comment by theosib-amazon** [comment] 2021-12-20 14:59
Hi. After figuring out that I had to specify the architecture explicitly, I was able to build Firecracker just using cargo. As far as I can tell, this time, it took the frame pointer setting from my environment.

**Comment by dianpopa** [comment] 2021-12-20 15:11
Thanks this confirms that we might be having an issue with `devtool`. I will look into it and let you know.
Indeed, the default target build is `x86_64`. If you build on aarch64, you need to explicitly mention the architecture.

**Comment by dianpopa** [comment] 2021-12-20 15:37
I am not able to replicate the issue with `devtool` either. I printed the output of `cargo build` when building with `devtool` and I am able to see the `-C force-frame-pointers=yes` in the output. 
```
Running `rustc --crate-name firecracker --edition=2018 src/firecracker/src/main.rs --error-format=json 
--json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C panic=abort -C embed-bitcode=no
 -C debuginfo=2 -C metadata=bdc8f0349c1cda24 
...
 --extern vmm=/firecracker/build/cargo_target/aarch64-unknown-linux-musl/debug/deps/libvmm-fff8ffd3395b1ee9.rlib
 -C force-frame-pointers=yes`
```

Changes to replicate this can be checked out at [1].

@theosib-amazon what exactly do you mean by `aspect of my user environment isn't being copied into the docker container`? What is the expected behavior?

[1] - https://github.com/dianpopa/firecracker/tree/i2816

**Comment by theosib-amazon** [comment] 2021-12-20 15:46
I was not able to directly verify whether or not contents of `~/.cargo/config` were copied into the docker container. Qualitatively, what I observed was that I got better call tree info when I built using cargo outside of docker. However, there are other explanations. For example, default target is statically linked, while I specified to cargo that I wanted to use glibc and dynamic linking. That might explain the difference. Sorry if i sent you on a wild goose chase.

**Comment by dianpopa** [comment] 2021-12-20 15:58
I see, no worries. So, what I understand was your confusion is whether the docker container makes use of `~/.cargo/config`. Yes, the docker container sees it and makes use of it since it will mount the whole firecracker directory in the root of the container.
Now, if you wish to use `glibc` you can also do that with `devtool`:
```
./tools/devtool build --libc gnu
```
For specifying any other additional cargo argument, you can do it by simply separating them with a `--`:
`./tools/devtool build --libc gnu -- <cargo_arg>`.

Let me know if there is anything I can help with.

**Comment by dianpopa** [comment] 2021-12-23 10:02
Since no more help is required here, I will close the issue. @theosib-amazon feel free to re-open if something changes.

**Closed by dianpopa** 2021-12-23 10:02 UTC
Labels: Quality: Bug
