### ISSUE TITLE
MMDS: Investigate if it's more efficient to decouple the mmds rx from the tap rx

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#518] opened 2018-10-10 12:54 UTC
I believe that since mmds packets are scarce and relatively latency-insensitive, it could be beneficial to take their processing out of the network rx fastpath.

Another side-effect of current design is that a mmds packet can trigger a tap-rx in the tx path - this should work fine, but might impact performance positively or negatively, and should also be investigated.
More details:
```java
NetEpollHandler::process_tx() {
    // The MMDS network stack works like a state machine, based on synchronous calls, and
    // without being added to any event loop. If any frame is accepted by the MMDS, we also
    // trigger a process_rx() which checks if there are any new frames to be sent, starting
    // with the MMDS network stack.
    let mut process_rx_for_mmds = false;
    ...
    // An incoming frame for the MMDS may trigger the transmission of a new message.
    if process_rx_for_mmds {
        self.process_rx();
    }
}
```

**Comment by roypat** [comment] 2024-05-20 11:18
I am closing this as a duplicate of https://github.com/firecracker-microvm/firecracker/issues/1761, which is also tracking the decoupling of MMDS from the network device

**Closed by roypat** 2024-05-20 11:18 UTC
Labels: Priority: Low, Type: Enhancement
