### ISSUE TITLE
Compare block/net/vsock performance with new epoll handler

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1631] opened 2020-02-24 15:22 UTC
We should check that we didn't introduce regressions by switching to the new `EventManager` implementation.

**Comment by goandrei** [comment] 2020-03-09 09:44
PR for switching to the new implementation : #1618

**Comment by goandrei** [comment] 2020-03-09 09:58
First commit before decoupling : 8d48e730f2ea8fe524002643912049486e07528c
Last decoupling commit : 3eb926ccf47251bb6d90f341577407d65d6aed0d

**Comment by goandrei** [comment] 2020-03-11 08:10
Hi,

I have just finished the performance testing on block&net devices and you can find the result attached bellow. I ran each test(net,block) twice, 30 minutes each. 
[decoupling.zip](https://github.com/firecracker-microvm/firecracker/files/4316812/decoupling.zip)

**Comment by goandrei** [comment] 2020-03-11 14:47
Adding some plots on the results posted above.
[decoupling_plots.zip](https://github.com/firecracker-microvm/firecracker/files/4318880/decoupling_plots.zip)

**Comment by goandrei** [comment] 2020-03-12 09:51
Added a legend for the test case name and labels for block tests features.
[decoupling_plots.zip](https://github.com/firecracker-microvm/firecracker/files/4323439/decoupling_plots.zip)

**Comment by goandrei** [comment] 2020-03-16 11:57
Adding some updates & notes on the issue : 
- the network performance tests results don't show a high variation, so I think we can use them as a reference. It seems like there is a small degradation on the udp-g2h(UDP protocol, host to guest transmission).
- on the other hand, the block performance tests present big variations in some of the following test cases:512-randread, 512-read, 1024-readwrite, 4096-randread, 4096-read, 4096-readwrite(to be noticed that all of them are testing read or both read&write). The variations may be causes by I/O latencies of the normal disk. I am going to perform some more testing, but this time using a ramdisk which should provide more stable results. 

I will update this issue with the new results as soon as possible.

**Comment by goandrei** [comment] 2020-03-17 16:28
Test results for block device with ramdisk. They were ran on the same environment as mentioned before : 
[blk_ramdisk.zip](https://github.com/firecracker-microvm/firecracker/files/4344519/blk_ramdisk.zip)

**Comment by iulianbarbu** [comment] 2020-03-23 10:04
I've done multiple tests for assessing network device performance, for the inconclusive data pertaining UDP guest to host traffic, after decoupling. The resulted data does not indicate any regression for this case. My conclusion is that we do not have any network device performance degradation. However, we must investigate further the guest CPU performance, to understand why we have these variations. Attached, I've attached plots with network throughput for the udp-g2h-10000mbit/s use case (every iteration has 0 loss).

![udp-g2h-10000-plot](https://user-images.githubusercontent.com/14218860/77305087-1a7b4280-6cfe-11ea-99d6-84a6537ee56f.png)
![udp-g2h-10000-plot2](https://user-images.githubusercontent.com/14218860/77305099-2109ba00-6cfe-11ea-8465-045852b13511.png)
![udp-g2h-10000-30_iter-1_vcpu-plot](https://user-images.githubusercontent.com/14218860/77305113-26ff9b00-6cfe-11ea-879d-d4e0913e3535.png)

**Comment by gc-plp** [comment] 2020-03-27 23:47
I've attached a comparison of the block device performance, before and after decoupling using the same commits referenced here: https://github.com/firecracker-microvm/firecracker/issues/1631#issuecomment-596434252

##### Testing methodology
1. For each test type added in PR #1409, a 10 minute test was executed, on a commit before decoupling and on another commit after decoupling.
2. FIO was configured to output the bandwidth, iops and latency status every 1 second.
3. In parallel to the FIO process, every one second the guest CPU load was sampled.
4. The raw outputted data was parsed and grouped into a CSV. 
5. For each generated CSV, a graph has been created.

##### Result format 
Each graph is actually rendered as a HTML file and it contains all the generated measurements for each test. Since it's an interactive HTML, individual lines can be enabled or disabled in order to have a proper scale of the data.

[blk_compare.zip](https://github.com/firecracker-microvm/firecracker/files/4396318/blk_compare.zip)

**Comment by raduiliescu** [comment] 2020-04-13 09:13
We decided that for large block sizes there is a performance degradation of 6%. 
For all other cases there are situation where code after decoupling performs better and there are situation where the code before decoupling performs better. All within 3% range.
We can close this issue.

**Closed** 2020-04-13 09:13 UTC
Labels: Quality: Automated Testing
