### ISSUE TITLE
Bridge networking docs example

### ISSUE THREAD

**Issue by mccurdyc** [firecracker-microvm/firecracker#2618] opened 2021-06-10 11:06 UTC
Goal: I'd love to have VMs as just another device on my home network that I can ping from anywhere on my home network I.e., they are in the 192.168.1.0/24 subnet.

If someone could help me debug my issue, I'd love to contribute back docs to https://github.com/firecracker-microvm/firecracker/blob/main/docs/network-setup.md or maybe a new "bridge networking doc". 

The issue. In my guest, I can't ping my network's default gateway.

```
localhost:~# ping -c 3 192.168.1.1
PING 192.168.1.1 (192.168.1.1): 56 data bytes

(just hangs)

--- 192.168.1.1 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
```

Context:

I've seen a few examples suggesting to create a tap interface on the host (for the firecracker vm) and to then just add it to "an existing bridge" which just happens to be the docker default bridge.

* https://github.com/firecracker-microvm/firecracker/issues/711#issuecomment-443424063
* https://jvns.ca/blog/2021/01/23/firecracker--start-a-vm-in-less-than-a-second/

Egress to the internet works if I use the docker default bridge, but I want to use a bridge that I create from scratch on a host not running docker. Also using the docker bridge feels "magical". I tried reading about docker's default [iptables rules](https://docs.docker.com/network/iptables/) since I have the feeling this is why I can't ping my default gateway from my guest, but the docs weren't super explicit.

Thanks!

---

Details:

I have the following host configuration

```
...
2: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 7e:6f:1a:3e:47:25 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.165/24 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fe80::7c6f:1aff:fe3e:4725/64 scope link 
       valid_lft forever preferred_lft forever
3: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP group default qlen 1000
    link/ether fa:1c:de:23:df:c5 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::f81c:deff:fe23:dfc5/64 scope link 
       valid_lft forever preferred_lft forever
4: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP group default qlen 1000
    link/ether 1c:69:7a:a2:3e:dd brd ff:ff:ff:ff:ff:ff
    altname enp0s31f6
...
```

```
sudo iptables -L

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination 
```

```
sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  anywhere             anywhere 
```

In my guest I have

```
localhost:~# ip a
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:1c:de:23:df:c5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.167/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::f81c:deff:fe23:dfc5/64 scope link dadfailed tentative 
       valid_lft forever preferred_lft forever
localhost:~# ip r
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.167
```

**Comment by sandreim** [comment] 2021-06-14 08:46
Hi @mccurdyc! We'll take a look.

**Comment by mccurdyc** [comment] 2021-06-14 13:38
@sandreim let me know if you need more information, etc.! To be honest, this may not specifically be a firecracker issue and may actually be a general networking question. However, I do think there is value in having a (non-docker default) bridge network example for folks like myself :smile:.

Thanks!

**Comment by mccurdyc** [comment] 2021-06-16 12:37
@sandreim I think I've got this working via iptables rules to allow ICMP requests and replies and SNAT rules in the NAT table.

I will contribute documentation! Thank you for considering my issue even though it was not specific to firecracker.

**Comment by sandreim** [comment] 2021-06-16 16:41
> @sandreim I think I've got this working via iptables rules to allow ICMP requests and replies and SNAT rules in the NAT table.
> 
> I will contribute documentation (hopefully this week) and at that time close this issue! Thank you for considering my issue even though it was not specific to firecracker.

Happy to hear the issue is solved and thank you for providing this update 😄 . We're looking forward for your contribution on the networking docs.

**Comment by cheersalam** [comment] 2021-08-03 02:32
Is there any document now on bridge example?

**Comment by acatangiu** [comment] 2021-08-03 12:55
@mccurdyc do you still plan to contribute documentation on how to set up bridge networking?

**Comment by mccurdyc** [comment] 2021-08-03 13:11
@acatangiu yeah! I can get this added today. My hesitation was making a contribution that didn't follow best practices or only worked for me since I don't deeply understand what I'm doing in this regard.

@cheersalam I'll post some notes here today and if you would try them out and let me know if they work for you, I can open a PR with my notes. 

Thanks!

**Comment by dianpopa** [comment] 2021-08-09 14:54
> @cheersalam please try out my docs and let me know if you run into any issues!
> 
> ### Assumptions
> * My network/subnet is: `192.168.1.0/24`
> * My gateway is: `192.168.1.1`
> * I give my bridge interface the following IP: `192.168.1.165`
> 
> ### On the Host
> 1. Create a bridge interface
>    ```
>    # ip link add name br0 type bridge
>    ```
> 2. Create a tap interface
>    ```
>    # ip tuntap add tap0 mode tap
>    ```
> 3. Set tap interface up
>    ```
>    # ip link set tap0 up
>    ```
> 4. Add tap interface to the bridge
>    ```
>    # ip link set dev tap0 master br0
>    ```
> 5. Define an IP address in your network for the bridge.
>    For example, if my gateway were on `192.168.1.1` and I wanted to use this for getting dynamic IPs, I would
>    want to give my bridge and IP address in the `192.168.1.0/24` subnet.
>    ```
>    # ip address add 192.168.1.165/24 dev br0
>    ```
> 6. Add firewall rules to allow traffic to be routed to the guest
>    ```
>    # iptables -t nat -A POSTROUTING -o br0 -j MASQUERADE
>    ```
> 7. Additionally, ensure you do the steps documented for enabling IP forwarding to the guest [in the Network Setup docs](https://github.com/firecracker-microvm/firecracker/blob/main/docs/network-setup.md).
>    ```
>    # echo '1' | sudo tee /proc/sys/net/ipv4/ip_forward
>    # sudo sysctl -w net.ipv4.ip_forward=1
>    ```
> 
> ### On the Guest
> 1. Define an unused IP address --- in the bridge's subnet e.g., `192.168.1.0/24` for the guest's ethernet interface.
>    This is also documented [in the Network Setup docs](https://github.com/firecracker-microvm/firecracker/blob/main/docs/network-setup.md).
>    _Note: Alternatively, you could rely on DHCP for getting a dynamic IP address from your gateway._
>    ```
>    # ip addr add 192.168.1.169/24 dev eth0
>    ```
> 2. Set the interface up.
>    ```
>    # ip link set eth0 up
>    ```
> 3. Create a route to the bridge device
>    ```
>    # ip r add 192.168.1.1 via 192.168.1.165 dev eth0
>    ```
> 4. Create a route to the internet via the bridge
>    ```
>    # ip r add default via 192.168.1.165 dev eth0
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    When done, your route table should look similar to the following:
>    ```
>    # ip r
>    default via 192.168.1.165 dev eth0
>    192.168.1.0/24 dev eth0 scope link
>    192.168.1.1 via 192.168.1.165 dev eth0
>    ```
> 5. Add your nameserver to `resolve.conf`
>    ```
>    # cat /etc/resolv.conf
>    nameserver 192.168.1.1
>    ```
> 6. Setup local DNS via `/etc/hosts`
>    ```
>    # cat /etc/hosts
>    127.0.0.1 localhost
>    ::1 localhost
>    127.0.1.1   <your guest's hostname>.localdomain
>    ```
> 
> ### Cleanup Host
> TODO

@mccurdyc your documentation looks good to me. I encourage you to post a PR with them. My suggestion would be to add the additional setup related to the bridge in the "Advanced" sections that we have in our [network-setup](https://github.com/firecracker-microvm/firecracker/blob/main/docs/network-setup.md#on-the-host). For example, I would say:

### On the host....


*Advanced:*  In case you want to use a bridge to communicate with the microVM, you need to do the following additional setup:
1. Create a bridge interface
2. Add tap interface to the bridge
3. Add firewall rules  on the bridge to allow traffic to be routed to the guest
4. ensure you do the steps documented for enabling IP forwarding to the guest
....

### In the guest
....

*Advanced:*  In case you want to use a bridge to communicate with the microVM, you need to do the following additional setup:
1. Create a route to the bridge device
2. ....


How does this sound to you?

**Comment by mccurdyc** [comment] 2021-08-09 16:43
@dianpopa that sounds great! I will try to open a PR this evening.

**Comment by mccurdyc** [comment] 2021-08-09 16:45
I also wanted to share helpful, related references in this issue which may not be included in the PR:

- https://gitlab.com/ongresinc/blog-posts-src/-/tree/master/202012-firecracker_cloud_image_automation
- https://ongres.com/blog/automation-to-run-vms-based-on-vanilla-cloud-images-on-firecracker/

I discovered these after figuring out the hard way, but these helped confirm my reduced set of commands necessary.

**Comment by mccurdyc** [comment] 2021-08-10 01:35
@dianpopa I opened the above PR, but want to give it one last round of testing / improvements in the morning.

**Comment by cheersalam** [comment] 2021-08-10 06:16
@mccurdyc Its not working for me. I am trying on VMWare VM. two interfaces are created in example above, br0 and tap0 on host, where are these used in firecracker VM?

**Comment by acatangiu** [comment] 2021-08-10 09:11
@cheersalam you mean it's not working with Firecracker or not working with VMWare?

Also be aware that running nested virtualization (for example Firecracker under VMWare) _might_ work but is not officially supported by us.

**Comment by dianpopa** [comment] 2021-09-07 13:25
@cheersalam if you are still experiencing issues with your setup, please join our [slack channel](https://firecracker-microvm.slack.com/) and let us know the details of your setup so we can help you. 
Closing this issue for the moment since  bridge documentation is now merged.

**Closed by dianpopa** 2021-09-07 13:25 UTC
