### ISSUE TITLE
Integration tests do not fail when memory threshold is exceeded

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#811] opened 2019-01-04 10:47 UTC
The `exit(-1)` in the memory monitor thread is not causing the tests to fail. Tested by setting the memory threshold to 0 and running an integration test. The usage is printed as an error message but the tests pass.

**Comment by andreeaflorescu** [comment] 2019-01-04 10:48
Duplicate of: https://github.com/firecracker-microvm/firecracker/issues/521

**Closed** 2019-01-04 10:48 UTC
Labels: Priority: High, Quality: Bug, Quality: CI
