### ISSUE TITLE
High CPU usage on host with intensive block I/O in guest

### ISSUE THREAD

**Issue by aldem** [firecracker-microvm/firecracker#715] opened 2018-11-30 23:47 UTC
I did some benchmarking of block I/O (just dd to /dev/null the whole device), and this produced average CPU usage ca. 100% (i.e. one core used completely) on host (with transfer rate ca. 100 MB/s).

When I have tried this on QEMU + virtio in guest (same host & guest image, and same backing file for block device, caches dropped), the CPU usage was below 5%.

Is this expected behavior (due to process operating in user-space) or there is a way/plan to optimize it? If block I/O so significantly loads host system, running multiple instances could quickly deplete host CPU resources, at least for periods with intensive guest I/O (backups, database, housekeeping etc).

**Comment by raduweiss** [comment] 2018-11-30 23:50
Can you give us more details about how you tested?

As per the [spec file](https://github.com/firecracker-microvm/firecracker/blob/master/SPECIFICATION.md), we're seeing the guest achieving up to 1 GiB/s storage throughput by using <= 70% a host CPU core for block device emulation.

**Comment by aldem** [comment] 2018-12-01 01:03
I have a regular Proxmox system (i7-6700 32GB RAM) running PVE kernel 4.15.18-30 (most recent) with QEMU 2.8
As to firecracker, I use binary relase 0.11.0. System is for experiments so it does not have any load.

I create VM providing it backing file for block I/O which has current Ubuntu 18.04 (10 GB file on SATA drive), and a custom kernel (most hardware stuff removed, virtio + virtblk included statically) compiled from sources (4.19.5). CPU is configured with 2 cores, ht disabled, template C3 and 1G RAM.

Once it boots, I drop caches on the host and in the guest (echo 3 >/proc/sys/vm/drop_caches), then execute dd in the guest:
```
# time -p dd if=/dev/vda iflag=direct of=/dev/null bs=1M status=progress
10402922496 bytes (10 GB, 9.7 GiB) copied, 39 s, 267 MB/s
10240+0 records in
10240+0 records out
10737418240 bytes (11 GB, 10 GiB) copied, 39.7241 s, 270 MB/s
real 39.82
user 0.05
sys 20.40
```
While it runs, I observe firecracker process usage using top, and overall CPU usage in netdata.
Process CPU usage jumps randomly from 25% to 130%.

Then I start the image in QEMU (standard ubuntu kernel 4.15.0, virtio block device) and repeat cache drops and dd in qemu guest:
```
# time -p dd if=/dev/vda iflag=direct of=/dev/null bs=1M status=progress
9055502336 bytes (9.1 GB, 8.4 GiB) copied, 21 s, 431 MB/s
10240+0 records in
10240+0 records out
10737418240 bytes (11 GB, 10 GiB) copied, 21.6709 s, 495 MB/s
real 21.77
user 0.00
sys 0.26
```
And again, while it runs, I check kvm/qemu usage in top and in net data - it is around 5% most of the time with rare peaks to 25%. When I ran this on the host itself, resulst were very close, only CPU usage was lower.

To make it more visual, netdata graph:

![image](https://user-images.githubusercontent.com/754722/49321998-b41c5080-f50b-11e8-8216-a2db1ba5651d.png)

This is CPU load collected on the host (1s sampling rate), first set of peaks is firecracker, second (much smaller) is qemu.

Average transfer rate is so high because the file is sparse and most of it has zeros. 

Yes, kernels are different, though I believe that this does not make big difference, but I can rerun with identical kernels if needed.

**Comment by alexandruag** [comment] 2018-12-01 02:30
Hi, can you also please give us more details about how you use QEMU to start the VM with the image?

**Comment by raduweiss** [comment] 2018-12-01 12:38
Another idea, to remove variables from the equation: Use a ram-disk for the file system.

**Comment by aldem** [comment] 2018-12-01 12:59
I am afraid that testing with RAM is a bit tricky, as reading 10GB takes just 1 second, not enough to produce any statistically significant result, and I have only 32GB, so even this would be too short.

What is most important, though, is the CPU usage while doing normal I/O - it should be low as most of the time system is waiting for completion.

And this is my full qemu configuration which I used to test:

```
/usr/bin/kvm -id 218 -name u1804 -chardev socket,id=qmp,path=/var/run/qemu-server/218.qmp,server,nowait \
  -mon chardev=qmp,mode=control -chardev socket,id=qmp-event,path=/var/run/qmeventd.sock,reconnect=5 \
  -mon chardev=qmp-event,mode=control \
  -pidfile /var/run/qemu-server/218.pid \
  -daemonize \
  -smbios type=1,uuid=149fb932-53dc-4341-8ba8-9b574dce3350 \
  -smp 4,sockets=1,cores=4,maxcpus=4 \
  -nodefaults -boot menu=on,strict=on,reboot-timeout=1000,splash=/usr/share/qemu-server/bootsplash.jpg \
  -vnc unix:/var/run/qemu-server/218.vnc,x509,password \
  -cpu kvm64,+pcid,+lahf_lm,+sep,+kvm_pv_unhalt,+kvm_pv_eoi,enforce \
  -m 4096 -k de \
  -device pci-bridge,id=pci.1,chassis_nr=1,bus=pci.0,addr=0x1e -device pci-bridge,id=pci.2,chassis_nr=2,bus=pci.0,addr=0x1f \
  -device piix3-usb-uhci,id=uhci,bus=pci.0,addr=0x1.0x2 \
  -device usb-tablet,id=tablet,bus=uhci.0,port=1 \
  -device VGA,id=vga,bus=pci.0,addr=0x2 \
  -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x3 \
  -drive if=none,id=drive-ide2,media=cdrom,aio=threads \
  -device ide-cd,bus=ide.1,unit=0,drive=drive-ide2,id=ide2,bootindex=200 \
  -drive file=/raid/vz/afc-arch.ext4,if=none,id=drive-virtio0,format=raw,cache=none,aio=native,detect-zeroes=on \
  -device virtio-blk-pci,drive=drive-virtio2,id=virtio0,bus=pci.0,addr=0xa \
  -netdev type=tap,id=net0,ifname=tap218i0,script=/var/lib/qemu-server/pve-bridge,downscript=/var/lib/qemu-server/pve-bridgedown,vhost=on \
  -device virtio-net-pci,mac=5A:3E:39:1F:F8:24,netdev=net0,bus=pci.0,addr=0x12,id=net0,bootindex=300 -machine type=pc
```

Nothing extraordinary here, not even dedicated I/O thread and no cache.

**Comment by alexandruag** [comment] 2018-12-01 14:34
Sorry, this is just a drive-by comment until we have a bit more time to look into this: what is the `detect-zeroes=on` parameter supposed to do? A cursory glance at the QEMU docs doesn't tell that much. If it's not too much hassle, could you have another look at QEMU performance with that thing off?

**Comment by aldem** [comment] 2018-12-01 15:16
I doubt that this parameter has any effect:

`detect-zeroes is "off", "on" or "unmap" and enables the automatic conversion of plain zero writes by the OS to driver specific optimized zero write commands.`

And I only do reads - detecting zeros on reads is pointless.

**Comment by aldem** [comment] 2018-12-01 21:12
It has to be some kernel option, which affects performance. Using hello-vmlinux kernel from Amazon, I am able to reach performance comparable to that of KVM/QEMU, while stripped custom kernel behaves differently. I even tried to use same kernel version (4.14.85), but it didn't help either.

Is there any chance to get kernel config for hello-vmlinux, so I could compare it to mine?

**Comment by raduweiss** [comment] 2018-12-02 03:42
@aldem yes, you can find it here: https://github.com/firecracker-microvm/firecracker/blob/master/resources/microvm-kernel-config

**Comment by aldem** [comment] 2018-12-02 14:09
Ok, thank you. Though I could not figure out (yet) what was the parameter (there are plenty which are different), but at least I am able to make proper testing - with this config performance is much better.

This time I used null_blk device (250G of nulls), both for qemu and firecracker. Since firecracker uses host cache (no O_DIRECT on open), I enabled host caching for qemu too.

fc: average 2.5 GB/s
qemu: average 4.9 GB/s

qemu consumes a bit more CPU, though, so I guess it is more or less fair difference. Results are consistent over multiple runs.

Retrying my old test, it seems that for normal SATA drive reads CPU usage is relatively low (~10% for ~100 MB/s), comparable with qemu and thus acceptable (for now).

As to caching behavior - using host cache for file I/O could be useful, though in most cases this is a waste of resources, since every device will be double cached - once on host and once in guest. This could be avoided by adding additional option (O_DIRECT) when opening host file (if supported), or even better - expose it to drive configuration request.

I will try to find which kernel configuration option is responsible for slowing things down, so anyone who is compiling their own kernel will be aware.

**Comment by raduweiss** [comment] 2018-12-02 14:53
You're right. We did talk briefly about `O_DIRECT` but since storage throughput was not a bottleneck for our use cases at the time, we focused on other things and never tested it. There's also the matter of how `O_DIRECT` affects the pages demand faulted by the guest over time. Firecracker uses demand fault paging by default, but (unless you use swap) guest pages once faulted are going to be resident in memory.

If you want to take a swing at this and run some tests that would be very much welcome 😃.

**Comment by aldem** [comment] 2018-12-02 16:13
Well, having an option in API to turn O_DIRECT on or off at will would greatly help in testing (and not only) :)

Unfortunately, rust for me is mostly read-only, so necessary changes are not so straight-forward - for someone who is familiar with language & code it might take 15-20 minutes, while I could spend hours. Direct I/O will be good option anyway, sooner or later.

**Comment by aldem** [comment] 2018-12-02 22:07
Still, something is odd with newer kernel - I re-ran the test with 4.19.5 after applying original config (my tests above were with 4.14.85), and results are a bit... strange (same setup):

```
01: 10737418240 bytes (11 GB, 10 GiB) copied, 10.8156 s, 993 MB/s
02: 10737418240 bytes (11 GB, 10 GiB) copied, 10.8775 s, 987 MB/s
03: 10737418240 bytes (11 GB, 10 GiB) copied, 10.8149 s, 993 MB/s
04: 10737418240 bytes (11 GB, 10 GiB) copied, 11.0314 s, 973 MB/s
05: 10737418240 bytes (11 GB, 10 GiB) copied, 12.302 s, 873 MB/s
06: 10737418240 bytes (11 GB, 10 GiB) copied, 14.3922 s, 746 MB/s
07: 10737418240 bytes (11 GB, 10 GiB) copied, 14.1835 s, 757 MB/s
08: 10737418240 bytes (11 GB, 10 GiB) copied, 16.3464 s, 657 MB/s
09: 10737418240 bytes (11 GB, 10 GiB) copied, 19.1263 s, 561 MB/s
10: 10737418240 bytes (11 GB, 10 GiB) copied, 20.4175 s, 526 MB/s
11: 10737418240 bytes (11 GB, 10 GiB) copied, 20.8751 s, 514 MB/s
12: 10737418240 bytes (11 GB, 10 GiB) copied, 20.6819 s, 519 MB/s
13: 10737418240 bytes (11 GB, 10 GiB) copied, 21.9322 s, 490 MB/s
14: 10737418240 bytes (11 GB, 10 GiB) copied, 21.7772 s, 493 MB/s
15: 10737418240 bytes (11 GB, 10 GiB) copied, 22.9503 s, 468 MB/s
16: 10737418240 bytes (11 GB, 10 GiB) copied, 23.7238 s, 453 MB/s
17: 10737418240 bytes (11 GB, 10 GiB) copied, 24.3499 s, 441 MB/s
18: 10737418240 bytes (11 GB, 10 GiB) copied, 24.3686 s, 441 MB/s
19: 10737418240 bytes (11 GB, 10 GiB) copied, 25.5423 s, 420 MB/s
20: 10737418240 bytes (11 GB, 10 GiB) copied, 25.429 s, 422 MB/s
```

This was produced by a loop running dd: `dd iflag=direct if=/dev/vdc of=/dev/null bs=1M count=10240 | sleep 1` (null_blk cached on host).

Over time, speed degrades (CPU usage stays a bit above 100%). When I restart VM, it recovers for a while, and then again degrades. Host/guest caches have no effect on this (in fact, guest cache is not used due to direct flag), and there is no activity besides firecracker.

At this point I have no ideas what it could be, but definitely related to kernel. There are many versions and features between 4.14 and 4.19, I could try to binsearch where it starts, but maybe someone has an idea?

**Comment by aghecenco** [comment] 2020-03-02 13:49
We are tracking both benchmarks (#1409, #1097, #1074) and optimizations (#1600) for the block device. These should shed more light on performance issues. In this particular case, the apparent conclusion is that the root cause wasn't in Firecracker at all (though the serial IO may have contributed to the high CPU). Closing for now, we should revisit after #1600 is in.

**Closed by aghecenco** 2020-03-02 13:49 UTC
Labels: Priority: Medium, Support: Question / Inquiry
