### ISSUE TITLE
[Bug] test_reinflate_balloon - intermittent failure on aarch64

### ISSUE THREAD

**Issue by iulianbarbu** [firecracker-microvm/firecracker#2257] opened 2020-11-04 15:46 UTC
## Describe the bug

Unstable test:

```
test_reinflate_balloon[debian_with_ssh_and_balloon]
   integration_tests/functional/test_balloon.py:330: in test_reinflate_balloon
      assert (third_reading - first_reading) <= 20000 E assert (154396 - 122916) <= 20000
```

## To Reproduce

Reproduced it once on: https://github.com/firecracker-microvm/firecracker/pull/2226, for aarch64.

## Expected behaviour

The test should always pass.

## Environment

CI for a PR.

## Additional context

N/A

## Checks
- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
~~- [] Are you certain the bug being reported is a Firecracker issue?~~

**Comment by pkj415** [comment] 2020-11-04 23:37
I am interested in working on this bug (have started looking into it), shall I take this up?

**Comment by georgepisaltu** [comment] 2020-11-05 11:40
Hi @pkj415 . We need to deploy a fix as soon as possible for this test as it is preventing PRs from getting merged, so we will handle it. However, this test needs a redesign as it is prone to intermittent failures and you can start working on that if you want.

Currently, `test_reinflate_balloon` in `test_balloon.py` has the purpose of ensuring that sequential inflate-deflate commands have the same effect on the VM's resident set size. In other words, if you inflate the balloon, then deflate it back to 0, the memory of the VM will be pretty much the same as when you perform additional inflation and deflation operations (with the same amount of memory being inflated). The test fails intermittently on ARM because the throughput of memory at inflate time is lower than on x86 machines and also the resident set size right after boot varies from run to run, so it's hard to establish a baseline.

The solution to the first problem is implementing a testing mechanism that, at a certain time interval, tries to assert the expected change in RSS happens. If it does, then go on with the rest of the test. If it doesn't, try again after the time interval passes, up to a certain number of tries, in which case it would fail. It would be nice if you could make the check generic, so we could use it in other tests as well.

The second problem requires the test to consistently start with the same RSS baseline so the checks are right each time we run the test. I suggest that before we do any actual testing, we check the RSS of the process and we increase it by the remaining amount up to a certain value, let's say 100 MiB. So, in this case, if we start the test and we see the VM has an RSS of 65 MiB, we dirty 35 MiB so that we get to 100 MiB and we carry on with the test from this baseline.

Let us know if you want to get involved.

**Comment by pkj415** [comment] 2020-11-05 17:15
@georgepisaltu Yes, I would like to get involved with this task to redesign the test and make it robust.

Right now, I am trying to reproduce this on arm emulated on qemu.

**Comment by pkj415** [comment] 2020-11-06 03:42
@georgepisaltu So, as you said -

1. Instead of all the sleep() calls in the code, we would like to add an iterative rss checker which keeps checking the rss value till it moves in the expected direction and stabilizes.
2. Also, we can specify a max timeout large enough to avoid cases where it doesn't ever stabilize.

I am able to run tests with the python debugger and now have a fair handle on the test code. I will make some preliminary code changes to get rid of the sleep() calls and send you an initial PR. Let me know what you think.

Adding to this - you also mentioned the issue of setting a baseline for the rss before performing any tests. I see that the tests read the initial value of rss using get_free_mem_ssh() and it would be ideal to also ensure this returns a stable value (right now we are calling this right after establishing the ssh connection). If we achieve returning a stable value from this function, all tests would be okay (I mean we might not have to then pick a specific base line number since we are only interested in the differences in rss). Let me know your thoughts for this as well.

**Closed** 2020-11-10 09:59 UTC
Labels: Quality: Bug
