### ISSUE TITLE
Latest Github release points incorrectly to v0.23.4

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2630] opened 2021-06-18 15:33 UTC
Our getting started guide download instructions use the latest tag and incorrectly download v0.23.4 instead of v0.24.4.
```
release_url="https://github.com/firecracker-microvm/firecracker/releases"
latest=$(basename $(curl -fsSLI -o /dev/null -w  %{url_effective} ${release_url}/latest))
arch=`uname -m`
curl -L ${release_url}/download/${latest}/firecracker-${latest}-${arch}.tgz \
| tar -xz
```

**Comment by alindima** [comment] 2021-06-22 06:15
Duplicate of https://github.com/firecracker-microvm/firecracker/issues/2448

**Closed by alindima** 2021-06-22 06:15 UTC
Labels: Documentation: Usage, Quality: Bug
