### ISSUE TITLE
[Bug] error[E0432]: unresolved import `vmm_sys_util::sock_ctrl_msg`

### ISSUE THREAD

**Issue by yurivict** [firecracker-microvm/firecracker#3368] opened 2023-01-14 19:33 UTC
```
error[E0432]: unresolved import `vmm_sys_util::sock_ctrl_msg`
  --> /usr/ports/emulators/firecracker/work/micro-http-4b18a043e997da5b5f679e3defc279fec908753e/src/connection.rs:16:19
   |
16 | use vmm_sys_util::sock_ctrl_msg::ScmSocket;
   |                   ^^^^^^^^^^^^^ could not find `sock_ctrl_msg` in `vmm_sys_util`

error[E0432]: unresolved import `vmm_sys_util::sock_ctrl_msg`
  --> /usr/ports/emulators/firecracker/work/micro-http-4b18a043e997da5b5f679e3defc279fec908753e/src/server.rs:15:19
   |
15 | use vmm_sys_util::sock_ctrl_msg::ScmSocket;
   |                   ^^^^^^^^^^^^^ could not find `sock_ctrl_msg` in `vmm_sys_util`

error[E0432]: unresolved import `vmm_sys_util::epoll`
  --> /usr/ports/emulators/firecracker/work/micro-http-4b18a043e997da5b5f679e3defc279fec908753e/src/server.rs:17:5
   |
17 | use vmm_sys_util::epoll;
   |     ^^^^^^^^^^^^^^^^^^^ no `epoll` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `micro_http` due to 3 previous errors
```

rust-1.66.0
FreeBSD 13.1

**Comment by roypat** [comment] 2023-01-18 08:35
Hi yurivict, I'm closing this as a duplicate of https://github.com/firecracker-microvm/micro-http/issues/34, please see my explanation there on why firecracker will not compile for a FreeBSD target, and why this outside our support policy.

**Closed by roypat** 2023-01-18 08:35 UTC
Labels: Quality: Bug
