### ISSUE TITLE
Include an SSH example into getting started

### ISSUE THREAD

**Issue by nmanthey** [firecracker-microvm/firecracker#1357] opened 2019-10-28 09:56 UTC
Dear Firecracker Team,

I was starting to look into how to use firecracker, and failed to find getting started documentation that is simple enough to help me setting up my first VM that I can communicate to via SSH.

Would it be possible to include such a scenario into onboarding material, that is placed prominently to help new comers jump in quickly? Eventually, providing scripts that run all the commands from the current getting-started.md docs might also be handy, so that the full tutorial can be consumed easily. Thanks!

Best,
Norbert

PS: I found #711, but think having all of the above implemented in an easy to consume flow would still be a good contribution to enable more people start using firecracker.

**Comment by nmanthey** [comment] 2019-10-29 22:25
I am currently not actively pursuing setting up a guest with SSH access to
the host, so it is not a high priority for me.

However, I can imagine being able to log into the guest from the host is a
nice state to be in when starting to explore whether firecracker is the
right technology to use. Hence, I think it would make a nice addition to
your onboarding docs. If that comes in a scripted way, that would allow me
to come back and play around easily next time ;).

Best,
Norbert

**Comment by dianpopa** [comment] 2020-01-20 13:27
Duplicate of #1418.

**Closed by dianpopa** 2020-01-20 13:27 UTC
Labels: Contribute: Good First Issue, Contribute: Help Wanted, Documentation: Usage, Priority: Low
