### ISSUE TITLE
docs: Document Firecracker Entropy Approach and Practical Use

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#663] opened 2018-11-27 12:30 UTC
We got this very good question on Slack:

> Things to add to the FAQ: What kind of entropy source(s) are available to the guest? Are RdRand &/ rdseed available? VirtIO RNG?

Since we spent some time thinking about this, we should document the answer (probably in the FAQ).

**Comment by jeromegn** [comment] 2019-04-08 14:24
Not sure if this is the right place, but I found a workaround for the low initial entropy. It's not a great fix as I don't know how could it is long-term... somebody who knows more about this can help fill in the gaps.

I created a go program, translated from [this python script](https://github.com/linuxkit/linuxkit/issues/3096#issuecomment-403301359), which can be statically compiled and ran sometime during the init phase: https://gist.github.com/jeromegn/ba3f694412979d21dafc9d625b8fcf04 (the translation might be wrong, I'm not great at python!)

Example output during init:

```
[    0.264564] random: crng init done
Finished entropizing with 2272 of bad entropy. took 3.949527ms
```

Without this, a lot of applications simply won't run right. Hope this helps other people struggling with this.

**Comment by raduweiss** [comment] 2019-04-09 07:32
> Finished entropizing with 2272 of bad entropy. took 3.949527ms

@jeromegn taking a look at the script that message is very real. It's bad entropy, which should not be used for *anything* related to cryptography.

**Comment by raduweiss** [comment] 2019-04-10 09:38
Yeah, I think we need to do better here. I think at a minimum we need to have a doc with some suggestions how to seed a fresh microVM with good entropy (which becomes really critical if you start lots of microVMs).

We'll look into the possibility of actually building a feature to address this in a painless way.

**Comment by raduweiss** [comment] 2019-04-10 20:30
Quick answer in case it unblocks anyone: It looks like starting [rngd](https://linux.die.net/man/8/rngd) very early in the guest OS boot sequence is a good solution for regular use cases (e.g., SSH, TLS). This goes if it's just run once on guest OS boot, and even if there are lots and lots of microVMs on a host.

This will be expanded upon when the PR associated with this issue comes up.

**Comment by raduweiss** [comment] 2019-04-22 10:50
Another option is to pass some bites from the host during the microVM creation to the guest (e.g., via writing them in a guest-visible file, or making them available in the MMDS).

**Comment by petreeftime** [comment] 2019-04-24 10:54
Probably, the correct way to go about this is to add `RANDOM_TRUST_CPU` to the default kernel config for firecracker. See: https://lwn.net/Articles/760584/.

**Comment by jeromegn** [comment] 2019-04-24 12:00
@petreeftime adding `random.trust_cpu=on` to the boot parameters does not appear to help. I'm not sure using `CONFIG_RANDOM_TRUST_CPU` would help if the boot param did not. Could be worth a shot though.

**Comment by petreeftime** [comment] 2019-04-24 12:17
`random.trust_cpu` is pretty new, it's was first available in Linux 4.19: https://github.com/torvalds/linux/commit/9b25436662d5fb4c66eb527ead53cab15f596ee0. You should see this message if it was activated: `random: crng done (trusting CPU's manufacturer)`.

**Comment by jeromegn** [comment] 2019-04-24 12:58
@petreeftime thanks a lot! I just compiled a 4.19.36 kernel with the config in this repo and then booted with the random.trust_cpu=on param and it worked! way faster boot.

**Comment by wahern-splunk** [comment] 2019-08-05 22:18
What's wrong with virtio-rng? https://wiki.qemu.org/Features/VirtIORNG

**Comment by bbros-dev** [comment] 2020-03-14 17:42
Just a note that having low/zero entropy on a VM can be good.  

For instance, this 'feature' of the firecracker VM allowed us to isolate the cause of what were random instances of terraform just hanging (Terraform issue [#24375](https://github.com/hashicorp/terraform/issues/24375)).

When we got terrafom on its own in the VM the hanging became reproducible..... the hanging was caused by waiting for the kernel entropy to reach a certain level.  Which it never did.

`rng-tools start` and the hanging went away.

Just a war story to hopefully persuade you that whatever you add to increase entropy should be easily turned off.

I'd argue for the default behavior to be: no source of increased entropy, with some easy way to turn it on (and back off).

**Comment by bbros-dev** [comment] 2020-03-14 18:00
I'd also like to cite issue #325 as another data point in having zero/low entropy as a default.  
While @sipsma was unhappy that his agent started to hang out of nowhere, the consistently low entropy also allowed him to isolate  the underlying source (3rd party library that had introduced a reliance on the kernel level of entropy)

It is not uncommon, and once you know that a likely source of very early hanging, or seemingly random hanging, is the level of entropy you can isolate the cause (`strace`, `gdb`).

However, if the default is to have high levels on entropy injected as the default you are back to square one of having random hanging events (whenever the start entropy is still too low) that you can never reproduce to prove it is application/library xyz.

**Comment by bbros-dev** [comment] 2020-03-14 18:13
For another data point in favor of consistently low entropy is  [comment](https://github.com/firecracker-microvm/firecracker-demo/issues/13#issuecomment-520003716) in [firecracker-demo issue #23](https://github.com/firecracker-microvm/firecracker-demo/issues/13) also makes clear that as long as you can reproduce the low entropy condition you can get an error msg (or `strace` or `dbg` output) showing you the source of the behavior is the low entropy of the system.  Remedies are well known.

**Comment by raduweiss** [comment] 2020-03-15 09:25
@bbros-dev that's an interesting angle. We'll keep it in mind.

**Comment by bbros-dev** [comment] 2020-06-14 12:03
Just a note that it appears the kernel is moving towards removing the blocking pool of random numbers.
Thankfully it sounds like the kernel authors are going to try to remove the kernel from the random numbers game - placing onus on user space.

When this comes to pass it is likely VM guest users are going to look to the VM host to expose and RNG hardware it has.
It is unlikely cloud vendors are going to step where the kernel fears to tread.

Either way it will be useful to document firecracker best practices for user provided random seeds/entropy - ideally KIS.

**Comment by petreeftime** [comment] 2020-06-15 14:00
I am reading the article as the opposite: the kernel's CSPRNG is good enough that there's no need to have a special blocking pool and can safely rely on urandom for entropy for all things. I would advise towards adding an optional virtio-rng device to Firecracker that can be used to seed the guest CSPRNG with host entropy on boot or periodically.

**Comment by bbros-dev** [comment] 2020-06-15 21:46
>I am reading the article as the opposite: the kernel's CSPRNG is good enough

From Lutomirski's patch which, at the time of writing, seems headed for mainline (bold added):

> >It adds getentropy(..., GRND_INSECURE).  This causes getentropy to
always return *something*.  **There is no guarantee whatsoever** that
the result will be cryptographically random or even unique, but the
kernel will give the best quality random output it can.  The name is
a big hint: the resulting output is INSECURE.

I think if the kernel core is not guaranteeing unique or even a 'cryptographically random' RN it would be a mistake (caveats follow) to add an layer of indirection to a VM that suggests there is a random source available.  The caveats are that the device will return some **`thing`** if:

1. it is connected to a hardware device on the host.
1. It is provided with seed values by the user and the user agrees to take responsibility to provide some way of maintaining a pool of random data; `haveged`, `rng-tools`, etc., or some such utility.

What that **`thing`** is should be for the the hardware provider to account for, or the user to take responsibility for if they insist on using virtio-rng without a hardware source.

The issue I've flag is that right now the user can't just provide some random data at startup, and dust their hands, they have to provide code to update the entropy counter or they (more likely some library they use) will still block on `/dev/random`. 
Yes this blocking behavior seems destined to change, but its not because the kernel has come up with some way of giving endless random data - rather they've stepped aside (correctly in my view) and pushed responsibility to the user side to determine if the data is random or not **for their purposes**.

Remember with Firecracker we're in a fairly unique position, the keyboard, if present, has one key (IMO this is good an should not change), you can run an app from memory so your give up the disk activity as an entropy source, effectively leaving you with device events at 4 unknown *bits* per event.

Since we're talking about documentation maybe it is worth thinking about removing the word **`generator`** since that gives the impression the device/Firecracker is actually creating (generating) something for you.

What I'm suggesting is a device that is  some kind of passthrough utility - passing through the hardware vendor data, or the data the user provided at startup.

**Comment by dianpopa** [comment] 2021-04-28 12:27
In the context of adding snapshot support for Firecracker, we have added documentation containing recommendations related to handling randomness when restoring
multiple microVM clones from a single snapshot: https://github.com/firecracker-microvm/firecracker/blob/main/docs/snapshotting/random-for-clones.md. These recommendations also apply for the general use case (i.e handling randomness for any microVM).

**Closed by dianpopa** 2021-04-28 12:27 UTC
Labels: Documentation: Design, Documentation: Usage, Priority: Medium
