### ISSUE TITLE
[arm64] Unexpected exit reason on vcpu run: SystemEvent

### ISSUE THREAD

**Issue by luxas** [firecracker-microvm/firecracker#1556] opened 2020-01-28 22:22 UTC
Hi! When I'm running Firecracker v0.20.0 on my RPi 4 2GB (I have Ignite running too, woot!), it always exits with a non-zero code for some reason.

I'm running the default getting started guide, and using the pre-provided guest & rootfs kernels.
This is the configuration:

```json
{
  "boot-source": {
    "kernel_image_path": "/home/pi/fc-test/hello-vmlinux.bin",
    "boot_args": "keep_bootcon console=ttyS0 reboot=k panic=1 pci=off"
  },
  "drives": [
    {
      "drive_id": "rootfs",
      "path_on_host": "/home/pi/fc-test/hello-rootfs.ext4",
      "is_root_device": true,
      "is_read_only": false
    }
  ],
  "machine-config": {
    "vcpu_count": 1,
    "mem_size_mib": 512,
    "ht_enabled": false
  }
}
```

Host kernel (config here: https://github.com/sakaki-/bcm2711-kernel-bis/blob/master/config):

```
# uname -a
Linux rpi-commander 4.19.97-v8-c8fbe9c63ce7-p4-bis+ #2 SMP PREEMPT Tue Jan 21 14:01:59 GMT 2020 aarch64 GNU/Linux
```

```console
$ rm -r /tmp/firecracker.socket && ./firecracker --api-sock /tmp/firecracker.socket --config-file config.json
[boot process]
$ # Connected to the guest now, kernel is default 4.14.x
$ reboot
[reboot process]
         Starting Reboot...
[   22.810582] reboot: Restarting system
[   22.810582] reboot: Restarting system
2020-01-28T22:15:19.318867294 [anonymous-instance:ERROR:src/vmm/src/vstate.rs:659] Unexpected exit reason on vcpu run: SystemEvent
2020-01-28T22:15:19.319116216 [anonymous-instance:ERROR:src/vmm/src/signal_handler.rs:37] Shutting down VM after intercepting a bad syscall (135).
```

What do you think might be the issue? I've tried many different configurations, but it always (regardless of clean/panic guest exit) returns `Unexpected exit reason on vcpu run: SystemEvent`

Help would be very appreciated, thank you!

cc @dianpopa @andreeaflorescu

**Comment by acatangiu** [comment] 2020-01-29 08:29
Closing this as a duplicate of #1456, we'll have a fix for it soon.

**Closed by acatangiu** 2020-01-29 08:29 UTC
