### ISSUE TITLE
Firecracker log messages come out of order (intermittent)

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#899] opened 2019-01-29 11:47 UTC
One of the logger integration tests failed once on an unrelated PR because the first message logged was not the one expected (it was the second one instead). It's an intermittent issue as the test normally passes.

```
_____________________ test_no_origin_logs[ubuntu_with_ssh] _____________________
integration_tests/functional/test_logging.py:76: in test_no_origin_logs
    show_origin=False
integration_tests/functional/test_logging.py:307: in _test_log_config
    assert line.startswith("Running Firecracker")
E   assert False
E    +  where False = <built-in method startswith of str object at 0x7f0198281198>('Running Firecracker')
E    +    where <built-in method startswith of str object at 0x7f0198281198> = '2019-01-28T20:46:52.492757112 [4e3803f8-2e5d-4bf0-8940-54a6e3c08d82:INFO] The API server received a synchronous Put r...metrics_fifo\\", \\"level\\": \\"Info\\", \\"show_level\\": true, \\"show_log_origin\\": false, \\"options\\": []}".\n'.startswith
```

**Comment by acatangiu** [comment] 2019-01-29 12:44
I think this was introduced recently, https://github.com/firecracker-microvm/firecracker/pull/895 just failed because of it, second PR today.

**Comment by serban300** [comment] 2019-01-31 15:42
PR for the fix: https://github.com/firecracker-microvm/firecracker/pull/909

Closing this as a duplicate of #906

**Closed by serban300** 2019-01-31 15:42 UTC
Labels: Priority: Medium, Quality: Bug
