### ISSUE TITLE
Process start-up time test failing

### ISSUE THREAD

**Issue by dhrgit** [firecracker-microvm/firecracker#873] opened 2019-01-22 12:36 UTC
`tests/integration_tests/performance/test_process_startup_time.py` is sometimes failing, even going as high as 200ms, while the expected maximum is 8ms.

I've seen higher values appear on desktop machines, while, on i3.metal instances, this test fails more rarely.

**Comment by andreeaflorescu** [comment] 2019-01-22 12:39
There are 2 PRs that failed with this error so far: https://github.com/firecracker-microvm/firecracker/pull/860 and https://github.com/firecracker-microvm/firecracker/pull/830.

**Comment by acipu-aws** [comment] 2019-01-23 16:08
I believe there are two separate issues here:
* one is that on platforms other than i3.metal the startup time is significantly larger, presumably because of system-specific configs (larger kernel, different CPUs etc.)
* the other is that the startup time is already close to the limit, so adding further features to the startup critical path gets the time over the limit. This issue can be solved by doing some profiling.

**Comment by serban300** [comment] 2019-02-04 14:36
When I run the jailer startup command directly on the desktop, process_startup_time_cpu_us is close to 8000 microseconds:

```
$ sudo ./target/x86_64-unknown-linux-musl/release/jailer --exec-file ./target/x86_64-unknown-linux-musl/release/firecracker --gid 1234 --id e55199cc-1d50-4e66-b9d1-cff2c5a671eb --node 0 --uid 1234 --chroot-base-dir /tmp/jailer --seccomp-level 2
cpu time spent before env.run command exec: 5698
cpu time spent before main start: 6863
process_startup_time_cpu_us : 8272
```

When I run it inside docker, process_startup_time_cpu_us is greater than 200000 microseconds:

```
/firecracker/build/cargo_target/x86_64-unknown-linux-musl/release/jailer --exec-file /firecracker/build/cargo_target/x86_64-unknown-linux-musl/release/firecracker --gid 1234 --id e55199cc-1d50-4e66-b9d1-cff2c5a671eb --node 0 --uid 1234 --chroot-base-dir /tmp/jailer --seccomp-level 2
cpu time spent before env.run command exec: 4664
cpu time spent before main start: 221729
process_startup_time_cpu_us : 222435
```

Almost the entire time is spent [here](https://github.com/firecracker-microvm/firecracker/blob/e05255f77552d1dca3993b5fec6c90f92cff9066/jailer/src/env.rs#L285-L297)

**Comment by serban300** [comment] 2019-02-04 16:07
strace -c output directly on the host:

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.000011           0       765           write
  0.00    0.000000           0       766           read
  0.00    0.000000           0        21         2 open
  0.00    0.000000           0      1039      1021 close
  0.00    0.000000           0         7           stat
  0.00    0.000000           0         6           fstat
  0.00    0.000000           0        78           mmap
  0.00    0.000000           0         1           mprotect
  0.00    0.000000           0         6           munmap
  0.00    0.000000           0         6           brk
  0.00    0.000000           0         8           rt_sigaction
  0.00    0.000000           0        10           rt_sigprocmask
  0.00    0.000000           0         1           ioctl
  0.00    0.000000           0         1           pipe
  0.00    0.000000           0         1           dup
  0.00    0.000000           0         1           getpid
  0.00    0.000000           0         1           socket
  0.00    0.000000           0         1           bind
  0.00    0.000000           0         1           listen
  0.00    0.000000           0         1           clone
  0.00    0.000000           0         2           execve
  0.00    0.000000           0        21           fcntl
  0.00    0.000000           0         2           chdir
  0.00    0.000000           0        12         6 mkdir
  0.00    0.000000           0         1           rmdir
  0.00    0.000000           0         4         2 readlink
  0.00    0.000000           0         1           fchmod
  0.00    0.000000           0         1           chown
  0.00    0.000000           0         1           setuid
  0.00    0.000000           0         1           setgid
  0.00    0.000000           0         1           setgroups
  0.00    0.000000           0         4           sigaltstack
  0.00    0.000000           0         1           mknod
  0.00    0.000000           0         1           pivot_root
  0.00    0.000000           0         2           prctl
  0.00    0.000000           0         2           arch_prctl
  0.00    0.000000           0         2           mount
  0.00    0.000000           0         1           umount2
  0.00    0.000000           0         2           futex
  0.00    0.000000           0         2           sched_getaffinity
  0.00    0.000000           0         2           set_tid_address
  0.00    0.000000           0         5           clock_gettime
  0.00    0.000000           0         2           epoll_ctl
  0.00    0.000000           0         1           unshare
  0.00    0.000000           0         2           epoll_pwait
  0.00    0.000000           0         1           eventfd2
  0.00    0.000000           0         1           epoll_create1
  0.00    0.000000           0         1           prlimit64
  0.00    0.000000           0         2           getrandom
------ ----------- ----------- --------- --------- ----------------
100.00    0.000011                  2802      1031 total

```

strace -c output in docker:

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.33    0.002956           0   1048591   1048573 close
  0.67    0.000020           0       763           write
  0.00    0.000000           0       764           read
  0.00    0.000000           0        21         2 open
  0.00    0.000000           0         7           stat
  0.00    0.000000           0         6           fstat
  0.00    0.000000           0        78           mmap
  0.00    0.000000           0         1           mprotect
  0.00    0.000000           0         6           munmap
  0.00    0.000000           0         6           brk
  0.00    0.000000           0         8           rt_sigaction
  0.00    0.000000           0        10           rt_sigprocmask
  0.00    0.000000           0         1           ioctl
  0.00    0.000000           0         1           pipe
  0.00    0.000000           0         1           dup
  0.00    0.000000           0         1           getpid
  0.00    0.000000           0         1           socket
  0.00    0.000000           0         1           bind
  0.00    0.000000           0         1           listen
  0.00    0.000000           0         1           clone
  0.00    0.000000           0         2           execve
  0.00    0.000000           0        21           fcntl
  0.00    0.000000           0         2           chdir
  0.00    0.000000           0        12         6 mkdir
  0.00    0.000000           0         1           rmdir
  0.00    0.000000           0         4         2 readlink
  0.00    0.000000           0         1           fchmod
  0.00    0.000000           0         1           chown
  0.00    0.000000           0         1           setuid
  0.00    0.000000           0         1           setgid
  0.00    0.000000           0         1           setgroups
  0.00    0.000000           0         4           sigaltstack
  0.00    0.000000           0         1           mknod
  0.00    0.000000           0         1           pivot_root
  0.00    0.000000           0         2           prctl
  0.00    0.000000           0         2           arch_prctl
  0.00    0.000000           0         2           mount
  0.00    0.000000           0         1           umount2
  0.00    0.000000           0         2           futex
  0.00    0.000000           0         2           sched_getaffinity
  0.00    0.000000           0         2           set_tid_address
  0.00    0.000000           0         5           clock_gettime
  0.00    0.000000           0         2           epoll_ctl
  0.00    0.000000           0         1           unshare
  0.00    0.000000           0         2           epoll_pwait
  0.00    0.000000           0         1           eventfd2
  0.00    0.000000           0         1           epoll_create1
  0.00    0.000000           0         1           prlimit64
  0.00    0.000000           0         2           getrandom
  0.00    0.000000           0         1         1 copy_file_range
------ ----------- ----------- --------- --------- ----------------
100.00    0.002976               1050351   1048584 total

```

The only big difference seems to be in the number of `close` errors: 1021 vs 1048573

**Comment by serban300** [comment] 2019-02-05 07:49
all the system calls executed from [here](https://github.com/firecracker-microvm/firecracker/blob/e05255f77552d1dca3993b5fec6c90f92cff9066/jailer/src/env.rs#L285-L297) until the start of firecracker main():

```
     0.000231 write(1, "cpu time spent until before env."..., 56) = 56
     0.000238 rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [], 8) = 0
     0.000129 rt_sigprocmask(SIG_BLOCK, ~[], NULL, 8) = 0
     0.000073 setgid(1234)              = 0
     0.000092 futex(0x805548, FUTEX_WAKE_PRIVATE, 2147483647) = 0
     0.000085 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
     0.000070 setgroups(0, NULL)        = 0
     0.000100 rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [], 8) = 0
     0.000065 rt_sigprocmask(SIG_BLOCK, ~[], NULL, 8) = 0
     0.000055 setuid(1234)              = 0
     0.000057 futex(0x805548, FUTEX_WAKE_PRIVATE, 2147483647) = 0
     0.000053 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
     0.000055 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
     0.000056 rt_sigaction(SIGPIPE, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x57b27a}, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x57b27a}, 8) = 0
     0.000075 execve("/firecracker", ["/firecracker", "--context={\"id\":\"e55199cc-1d50-4"...], 0x7ffc2ba5fc88 /* 13 vars */) = 0
     0.000592 mmap(NULL, 800, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f02ad94d000
     0.000080 arch_prctl(ARCH_SET_FS, 0x7f02ad94d220) = 0
     0.000052 set_tid_address(0x7f02ad94d260) = 802
     0.000061 readlink("/etc/je_malloc.conf", 0x7fffd38856a0, 4096) = -1 ENOENT (No such file or directory)
     0.000106 open("/proc/sys/vm/overcommit_memory", O_RDONLY) = -1 ENOENT (No such file or directory)
     0.000085 brk(NULL)                 = 0x21f7000
     0.000050 open("/sys/kernel/mm/transparent_hugepage/enabled", O_RDONLY) = -1 ENOENT (No such file or directory)
     0.000083 mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f02ad74d000
     0.000057 munmap(0x7f02ad74d000, 2097152) = 0
     0.000058 mmap(NULL, 4190208, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f02ad54e000
     0.000055 munmap(0x7f02ad54e000, 729088) = 0
     0.000073 munmap(0x7f02ad800000, 1363968) = 0
     0.000103 sched_getaffinity(0, 128, [0, 1, 2, 3, 4, 5, 6, 7]) = 64
     0.000065 brk(NULL)                 = 0x21f7000
     0.000048 brk(0x21f8000)            = 0x21f8000
     0.000068 rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x5edcac}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
     0.000063 rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
     0.000055 rt_sigaction(SIGSEGV, {sa_handler=0x553af0, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_SIGINFO, sa_restorer=0x5edcac}, NULL, 8) = 0
     0.000055 rt_sigaction(SIGBUS, {sa_handler=0x553af0, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_SIGINFO, sa_restorer=0x5edcac}, NULL, 8) = 0
     0.000053 sigaltstack(NULL, {ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}) = 0
     0.000056 mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f02ad94b000
     0.000054 sigaltstack({ss_sp=0x7f02ad94b000, ss_flags=0, ss_size=8192}, NULL) = 0
     0.000060 mmap(NULL, 2097152, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f02ad400000
     0.000053 mmap(0x7f02ad400000, 53248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad400000
     0.000081 mmap(0x7f02ad40d000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad40d000
     0.000064 mmap(0x7f02ad415000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad415000
     0.000066 mmap(0x7f02ad416000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad416000
     0.000082 mmap(0x7f02ad417000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad417000
     0.000068 mmap(0x7f02ad41a000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad41a000
     0.000068 mmap(0x7f02ad41f000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad41f000
     0.000064 mmap(0x7f02ad420000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad420000
     0.000068 clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=5, tv_nsec=434635660}) = 0
     0.000072 rt_sigaction(SIGSYS, {sa_handler=0x450fc0, sa_mask=~[RTMIN RT_1 RT_2], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x5edcac}, NULL, 8) = 0
     0.000093 mmap(0x7f02ad421000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad421000
     0.000063 mmap(0x7f02ad422000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad422000
     0.000063 mmap(0x7f02ad423000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad423000
     0.000056 mmap(0x7f02ad424000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad424000
     0.000054 mmap(0x7f02ad425000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad425000
     0.000060 mmap(0x7f02ad426000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad426000
     0.000071 getrandom("\xc8\xde\x02\x94\xc2\x98\x6e\xec\x90\x33\x23\x41\xed\xb1\x30\x0a", 16, GRND_NONBLOCK) = 16
     0.000077 mmap(0x7f02ad42b000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad42b000
     0.000083 mmap(0x7f02ad42c000, 28672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad42c000
     0.000122 mmap(0x7f02ad433000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad433000
     0.000070 mmap(0x7f02ad436000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f02ad436000
     0.000076 write(1, "cpu time spent before main start"..., 42) = 42
```

The problem is not in the linux system calls. It must be higher level.

**Comment by serban300** [comment] 2019-02-07 10:59
I missed a couple of things in the previous measurements and this led me to believe that ```CommandExt::exec()``` is causing the issue. But after adding measurements inside the rust stdlib, I realized ```CommandExt::exec()``` can't be blamed for this performance penalty. The actual issue is [this](https://github.com/firecracker-microvm/firecracker/blob/80128ea61b305a27df1f751d70415b04b503eae7/jailer/src/lib.rs#L329-L332)
here are some measurements:

```
[Jailer] absolute cpu time - before 'for i in 3..fd_size' 1874
[Jailer] absolute cpu time - after 'for i in 3..fd_size' 244837
```

This happens because the maximum number of opened file descriptors in the docker container is > 1 million on my machine. It also explains the huge number of calls to the `close` system call.

A fix could be to execute
```
ulimit -n 1024
```
inside the docker image

this significantly decreases the execution time:
```
[Jailer] absolute cpu time - before 'for i in 3..fd_size' 1604
[Jailer] absolute cpu time - after 'for i in 3..fd_size' 2563
```

**Comment by dhrgit** [comment] 2019-02-07 11:59
Ah, yes. There was a debate, a while ago, about the best way to close those fds. We went with blindly calling `close()` instead of parsing `/proc/self/fd`, for the simpler implementation and the mostly similar result.

Anyway, this should be easy enough to fix. I.e. when running the docker container, in `devtool`, we can set a lower limit for the max number of fds, similar to how we currently disable core dumps inside the container.

Also, excellent deep-dive, @serban300 !

**Comment by serban300** [comment] 2019-02-08 07:52
As discussed offline I proposed a fix that involves parsing `/proc/self/fd`. On my machine this reduces the startup time from 220-240ms to 7-15ms. I will continue to investigate this issue in order to understand if we can further reduce it in order to make the test succeed regularly.

**Comment by serban300** [comment] 2019-02-12 14:52
After pushing the fix on the master branch I am consistently getting startup times smaller then 8ms. Closing.

**Closed by serban300** 2019-02-12 14:52 UTC
Labels: Priority: Medium, Quality: Bug
