### ISSUE TITLE
SendCtrAltDel command line cannot close VMs.

### ISSUE THREAD

**Issue by rchatsiri** [firecracker-microvm/firecracker#1095] opened 2019-05-15 03:28 UTC
I'm found an issues after use command call API `SendCtrAltDel` on server. Currently instance use Linux version.

> Linux firework-vm01 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux 

Linux run under the VMWare ESXi version 6.5. This is log from console.  

``` 
$sudo curl --unix-socket /tmp/firecracker.socket -i \
>     -X PUT "http://localhost/actions" \
>     -H  "accept: application/json" \
>     -H  "Content-Type: application/json" \
>     -d "{
>              \"action_type\": \"SendCtrlAltDel\"
>     }"
HTTP/1.1 204 No Content
Date: Tue, 14 May 2019 12:16:55 GMT
```
Console prints result as below.

``` 2019-05-14T05:16:55.790607760 [anonymous-instance:WARN:devices/src/legacy/i8042.rs:146] Failed to trigger i8042 kbd interrupt (disabled by guest OS) ```

**Comment by dhrgit** [comment] 2019-05-15 11:54
@rchatsiri Do you have `i8042` and `atkbd` support enabled in the guest kernel? We have [this doc](https://developer.github.com/v3/repos/contents/#get-archive-link), describing the requirements for using `SendCtrlAltDel`.

**Comment by rchatsiri** [comment] 2019-05-20 15:49
I'm not found destination link from you reference. Grub changed configuration by use i8042 and atkbd parameter add to ``` /etc/default/grub ```. It didn't help to receive shutdown signal from firecracker api.

```
GRUB_CMDLINE_LINUX_DEFAULT="i8042.reset atkbd.reset i8042.nomux quiet"
```
The message show and error when we send action type is  ``` SendCtrlAltDel ```.
```
localhost login: 2019-05-20T08:29:24.859348473 [anonymous-instance:WARN:devices/src/legacy/i8042.rs:146] Failed to trigger i8042 kbd interrupt (disabled by guest OS)
```


Result of device message which command line filter type name i8042
```
$ sudo dmesg | grep i8042
[    1.317427] i8042: PNP: PS/2 Controller [PNP0303:KBC,PNP0f13:MOUS] at 0x60,0x64 irq 1,12
[    1.318148] serio: i8042 KBD port at 0x60,0x64 irq 1
[    1.318164] serio: i8042 AUX port at 0x60,0x64 irq 12
[    1.441112] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input0
[    1.642766] input: VirtualPS/2 VMware VMMouse as /devices/platform/i8042/serio1/input/input3
[    1.644114] input: VirtualPS/2 VMware VMMouse as /devices/platform/i8042/serio1/input/input2
```

**Comment by dhrgit** [comment] 2019-05-20 16:33
@rchatsiri Apologies, [this is the API doc](https://github.com/firecracker-microvm/firecracker/blob/master/docs/api_requests/actions.md#sendctrlaltdel). As per that doc, please try to add this to the guest kernel command line:

```
i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd
```

**Comment by progamer71** [comment] 2019-05-23 09:35
@rchatsiri I use this command, it work in my system.
curl --unix-socket /tmp/firecracker.socket -i \
    -X PUT 'http://localhost/boot-source'   \
    -H 'Accept: application/json'           \
    -H 'Content-Type: application/json'     \
    -d '{"kernel_image_path": "./vmlinux", "boot_args": "console=ttyS0 reboot=k panic=1 pci=off i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd"}'

**Comment by raduweiss** [comment] 2019-06-03 11:48
Closing for now since we've not heard back from @rchatsiri. Feel free to reopen if need be.

**Comment by mhhajeer** [comment] 2019-09-25 23:18
This is not working, I am having the same issue even after adding the command lines.

in my guest OS I see that it was added successfully 

localhost:~# cat /proc/cmdline
console=ttyS0 reboot=k panic=1 pci=off i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda rw virtio_mmio.device=4K@0xd0000000:5

it worth maybe to note that while booting the kernel and rootfs I downloaded from https://s3.amazonaws.com/spec.ccfc.min/img/hello/kernel/hello-vmlinux.bin & hello-rootfs.ext4

I see these modprobe failures as well 
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory

**Comment by dhrgit** [comment] 2019-09-26 08:09
@mhhajeer `SendCtrlAltDel` works by sending keyboard events (i.e. key presses) to the guest. Keyboard events in the guest are handled by the keyboard driver. That means you need a guest kernel with the `i8042` and `atkbd` drivers. [One such kernel](https://s3.amazonaws.com/spec.ccfc.min/img/x86_64/minimal_with_atkbd/kernel/vmlinux.bin) is used by our integration tests.

Check out [the docs section](../blob/master/docs/api_requests/actions.md#sendctrlaltdel) for more details.

**Comment by mhhajeer** [comment] 2019-09-26 18:04
I used the kernel provided by you in the comment. still didn't work. I will try building my own kernel with these options and will let you know what happens. 
I think the image "xenial.rootfs.ext4" provided in [readme](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#running-the-integration-test-suite) itself is missing the modules.

**Comment by mhhajeer** [comment] 2019-09-26 19:43
new Build of kernel with required drivers still have the same issue. Note that lsmod list no drivers loaded at all 
localhost:~# lsmod
Module                  Size  Used by    Not tainted

when issuing the halt action I still see this : 
localhost:~# 2019-09-26T12:34:56.291512200 [anonymous-instance:WARN:devices/src/legacy/i8042.rs:146] Failed to trigger i8042 kbd interrupt (disabled by guest OS)
2019-09-26T12:34:56.291644247 [anonymous-instance:WARN:devices/src/legacy/i8042.rs:146] Failed to trigger i8042 kbd interrupt (disabled by guest OS)
2019-09-26T12:34:56.291678715 [anonymous-instance:WARN:devices/src/legacy/i8042.rs:146] Failed to trigger i8042 kbd interrupt (disabled by guest OS)

**Comment by dhrgit** [comment] 2019-09-27 08:30
With the kernel I suggested, `i8042` and `atkbd` are built-in, not as modules. You won't see them showing up in the `lsmod` output.

If you `dmesg | egrep -i "i8042|kbd"` in the guest, you should see some info from the keyboard driver. If that doesn't show up, the guest kernel is not properly configured, and `SendCtrlAltDel` will not work.

**Comment by mhhajeer** [comment] 2019-09-27 18:33
your Kernel shows 
localhost:~# dmesg | egrep -i "i8042|kbd"
[    0.000000] Command line: console=ttyS0 reboot=k panic=1 pci=off i8042.noaux i8042.nomux i8042.reset i8042.nopnp i8042.dumbkbd root=/dev/vda rw virtio_mmio.device=4K@0xd0000000:5
[    0.000000] Kernel command line: console=ttyS0 reboot=k panic=1 pci=off i8042.noaux i8042.nomux i8042.reset i8042.nopnp i8042.dumbkbd root=/dev/vda rw virtio_mmio.device=4K@0xd0000000:5
[    0.617115] i8042: i8042 controller selftest timeout

**Comment by dhrgit** [comment] 2019-10-01 15:25
@mhhajeer Can you please provide the steps to reproduce this behaviour? I.e. Firecracker arguments, API calls, kernel binary, rootfs image, etc. I haven't been able to hit this issue on my own.

**Comment by mhhajeer** [comment] 2019-10-01 21:10
### **I followed the wiki link on git for getting started. so I used these commands** 

./firecracker --api-sock /tmp/firecracker.socket

### **then cloned the kernel and root fs from you and I also tried those commands below.** 

`arch=`uname -m`
  dest_kernel="hello-vmlinux.bin"
  dest_rootfs="hello-rootfs.ext4"
  image_bucket_url="https://s3.amazonaws.com/spec.ccfc.min/img"

  if [ ${arch} = "x86_64" ]; then
          kernel="${image_bucket_url}/hello/kernel/hello-vmlinux.bin"
          rootfs="${image_bucket_url}/hello/fsfiles/hello-rootfs.ext4"
  elif [ ${arch} = "aarch64" ]; then
          kernel="${image_bucket_url}/aarch64/ubuntu_with_ssh/kernel/vmlinux.bin"
          rootfs="${image_bucket_url}/aarch64/ubuntu_with_ssh/fsfiles/xenial.rootfs.ext4"
  else
          echo "Cannot run firecracker on $arch architecture!"
          exit 1
  fi

  echo "Downloading $kernel..."
  curl -fsSL -o $dest_kernel $kernel

  echo "Downloading $rootfs..."
  curl -fsSL -o $dest_rootfs $rootfs

  echo "Saved kernel file to $dest_kernel and root block device to $dest_rootfs."`

**### then I Set the kernel and rootfs . note that with default param and with the params you mentioned , both gave the same results "kernel params"** 

`arch=`uname -m`
  kernel_path="hello-vmlinux.bin"

  if [ ${arch} = "x86_64" ]; then
    curl --unix-socket /tmp/firecracker.socket -i \
        -X PUT 'http://localhost/boot-source'   \
        -H 'Accept: application/json'           \
        -H 'Content-Type: application/json'     \
        -d "{
              \"kernel_image_path\": \"${kernel_path}\",
              \"boot_args\": \"console=ttyS0 reboot=k panic=1 pci=off\"
         }"
  elif [ ${arch} = "aarch64" ]; then
      curl --unix-socket /tmp/firecracker.socket -i \
        -X PUT 'http://localhost/boot-source'   \
        -H 'Accept: application/json'           \
        -H 'Content-Type: application/json'     \
        -d "{
              \"kernel_image_path\": \"${kernel_path}\",
              \"boot_args\": \"console=ttyS0 reboot=k panic=1 pci=off i8042.noaux i8042.nomux i8042.reset i8042.nopnp i8042.dumbkbd\"
         }"
  else
      echo "Cannot run firecracker on $arch architecture!"
      exit 1
  fi


rootfs_path="hello-rootfs.ext4"
  curl --unix-socket /tmp/firecracker.socket -i \
    -X PUT 'http://localhost/drives/rootfs' \
    -H 'Accept: application/json'           \
    -H 'Content-Type: application/json'     \
    -d "{
          \"drive_id\": \"rootfs\",
          \"path_on_host\": \"${rootfs_path}\",
          \"is_root_device\": true,
          \"is_read_only\": false
     }"
`
**### then I started the VM** 

`curl --unix-socket /tmp/firecracker.socket -i \
    -X PUT 'http://localhost/actions'       \
    -H  'Accept: application/json'          \
    -H  'Content-Type: application/json'    \
    -d '{
        "action_type": "InstanceStart"
     }'`

**Comment by dhrgit** [comment] 2019-10-02 14:50
@mhhajeer If I understand this correctly, you are still using the `hello-vmlinux.bin` kernel, which as no i8042/atkbd support. I can replicate the problem with that kenel, which is to be expected.

The kernel I was suggesting is the one we use for testing `SendCtrlAltDel`, and which has i8042 and atkbd compiled in. This one: https://s3.amazonaws.com/spec.ccfc.min/img/x86_64/minimal_with_atkbd/kernel/vmlinux.bin .

**Comment by mhhajeer** [comment] 2019-10-02 18:37
@dhrgit I did in one experiment. however, this is not the only one I tried:
1. hello-vmlinux.bin 
2.  https://s3.amazonaws.com/spec.ccfc.min/img/x86_64/minimal_with_atkbd/kernel/vmlinux.bin 
3. compiled my own with CONFIG_SERIO_I8042 and CONFIG_KEYBOARD_ATKBD. 

all three experiments resulted in same outcomes.

your Kernel shows (exp 2) showed 
localhost:~# dmesg | egrep -i "i8042|kbd"
[ 0.000000] Command line: console=ttyS0 reboot=k panic=1 pci=off i8042.noaux i8042.nomux i8042.reset i8042.nopnp i8042.dumbkbd root=/dev/vda rw virtio_mmio.device=4K@0xd0000000:5
[ 0.000000] Kernel command line: console=ttyS0 reboot=k panic=1 pci=off i8042.noaux i8042.nomux i8042.reset i8042.nopnp i8042.dumbkbd root=/dev/vda rw virtio_mmio.device=4K@0xd0000000:5
[ 0.617115] i8042: i8042 controller selftest timeout

**Comment by dhrgit** [comment] 2019-10-02 19:39
@mhhajeer Unfortunately, I still can't reproduce the problem. Can you please try running our `SendCtrlAltDel` integration test on your machine and let me know if it passes?

I.e. - with Docker and git installed:
```bash
git clone https://github.com/firecracker-microvm/firecracker.git
firecracker/tools/devtool test -- integration_tests/functional/test_api.py::test_send_ctrl_alt_del
```

If the test passes, it will download:
- an atkbd-enable kernel to `firecracker/build/img/x86_64/minimal_with_atkbd/kernel/vmlinux.bin`; and
- a test rootfs to `firecracker/build/img/x86_64/minimal_with_atkbd/fsfiles/atkbd-rootfs.ext4`.

If the test passes, can you please try starting Firecracker with that kernel and that rootfs? Note that, in the example you provided, you were setting the kernel command line for aarch64, not for x86_64.

**Comment by mhhajeer** [comment] 2019-10-02 23:56
Great, this one is working. test passed and I copied the kernel and it worked :) big thanks. I am going to try again and compile my own kernel 
https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md

I will be using the .config provided here https://github.com/firecracker-microvm/firecracker/blob/master/resources/microvm-kernel-config 

and will let you know if it works. by the way, no kernel param used this time other than keep_bootcon console=ttyS0 reboot=k panic=1 pci=off , and it worked

**Comment by dhrgit** [comment] 2019-10-03 07:38
@mhhajeer If you start from our reference config for kernel v4.14.72, and add:

```
CONFIG_SERIO_I8042=y
CONFIG_KEYBOARD_ATKBD=y
```

then run `make vmlinux`, the kernel build system will guide you through adding the dependent options (like `CONFIG_SERIO=y`, since that's needed by `CONFIG_SERIO_I8042=y`).

The minimal diff that I got was:

```
CONFIG_INPUT_KEYBOARD=y
CONFIG_KEYBOARD_ATKBD=y
CONFIG_SERIO=y
CONFIG_SERIO_I8042=y
CONFIG_SERIO_LIBPS2=y
```

As for the additional kernel command line args, we are suggesting those just for a shorter boot time. `SendCtrlAltDel` will work just fine without them, but booting the microvm will take longer, if the kernel has to probe the i8042 during boot. Those args tell the kernel to skip that probing process.

**Comment by dhrgit** [comment] 2020-01-20 12:38
Closing as not reproducible. Please reopen if necessary.

**Closed by dhrgit** 2020-01-20 12:38 UTC
Labels: Support: Question / Inquiry
