### ISSUE TITLE
Improve failure message upon creation of vsock device

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#1279] opened 2019-09-23 12:37 UTC
If Vsock device creation fails (i.e `CreateVsockDevice`) is triggered, a error of this type will be returned upon `InstanceStart`:
```
curl --unix-socket /tmp/firecracker.socket -i      -X PUT "http://localhost/actions"      -H  "accept: application/json"      -H  "Content-Type: application/json"      -d "{  
            \"action_type\": \"InstanceStart\"
         }"
HTTP/1.1 400 Bad Request
Content-Type: application/json
Transfer-Encoding: chunked
Date: Mon, 23 Sep 2019 12:23:49 GMT

{
  "fault_message": "Cannot create vsock device."
}
```

That happens because [CreateVsockDevice](https://github.com/firecracker-microvm/firecracker/blob/master/vmm/src/vmm_config/instance_info.rs#L62) error does not propagate errors triggered inside the `devices` module.

**Comment by dhrgit** [comment] 2019-09-30 08:10
A quick note until we get this fixed in the code: more often than not, this error is caused by the vsock backend not being able to create and bind to the backing Unix socket (e.g. the backing Unix socket hasn't been removed between Firecracker invocations).

**Closed** 2019-10-03 07:46 UTC
Labels: Codebase: Usability, Quality: Bug
