### ISSUE TITLE
Create custom rootfs and kernel images docs are not complete

### ISSUE THREAD

**Issue by iulianbarbu** [firecracker-microvm/firecracker#1418] opened 2019-11-21 18:02 UTC
The docs that let you know [how to build a custom rootfs and vmlinux](https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md) are not complete in the idea that they do not show how to configure the VM after building both rootfs and vmlinux, and log in successfully inside the VM.

It would be nice to provide configuration for simple use cases like using a rootfs with ssh and a kernel built from linux git, and the setup that is needed in order to ssh into the VM with root user.

There is an issue on firecracker-demo repo, [#27](https://github.com/firecracker-microvm/firecracker-demo/issues/27#issue-525772440), which proves that the docs are not clear enough in the environment restrictions and common use cases for those who want to use Firecracker with rootfs & kernel built from zero.

**Comment by dianpopa** [comment] 2020-01-16 14:36
[This](https://github.com/marcov/firecracker-initrd) could be a great starting point. Actually that is the script that was used to create the initrd image for aarch64. The image is an alpine one with all packages needed. Maybe we can tweak it a little bit and be able to specify if the resulting image will contain an initrd or not.

**Comment by luxas** [comment] 2020-01-28 12:54
Ignite has some docs on how to do it too, e.g. in:
 - https://github.com/weaveworks/ignite/tree/master/images/kernel
 - https://github.com/luxas/ignite/tree/luxas/add_arm64/images/kernel (my temp. fork updated for arm64)
 - https://github.com/weaveworks/ignite/tree/master/images (for other OSes)

might be of interest :)

**Comment by alicelambda** [comment] 2020-10-28 00:35
Hello, I would like to work on this. From my understanding, the issue is that the docs should be extended to show how to configure and boot the vm after it is configured?

**Comment by serban300** [comment] 2020-10-28 12:30
Hi @alicelambda ! I talked with @iulianbarbu . This issue was more related to also configuring a ssh server in the example rootfs. But, on another thought, this is use-case specific and I don't know if it makes sense to include this in the Firecracker documentation. Closing for now.

**Closed by serban300** 2020-10-28 12:30 UTC
Labels: Contribute: Good First Issue, Documentation: Usage
