### ISSUE TITLE
Fircracker will crash when receving a signal

### ISSUE THREAD

**Issue by raduiliescu** [firecracker-microvm/firecracker#1604] opened 2020-02-13 15:31 UTC
Send any signal to a running Firecracker and it will crash with epoll interrupted error.
Epoll can be interrupted by signals and returns -EINTR. This should be not treated as error.

One related issue is that you are unable to do gdb attach.

**Comment by dianpopa** [comment] 2020-03-11 19:47
This seems to be a duplicate of a very old issue: #197. Since Firecracker has undergone massive refactoring since then, I will leave this one open as latest reference.

**Comment by acatangiu** [comment] 2020-03-16 16:53
Duplicate of #197

**Closed by acatangiu** 2020-03-16 16:53 UTC
Labels: Priority: Medium, Quality: Bug
