### ISSUE TITLE
Slack invite link does not work anymore

### ISSUE THREAD

**Issue by Furisto** [firecracker-microvm/firecracker#3976] opened 2023-07-19 10:06 UTC
# Describe the bug

The [slack invite](https://firecracker-microvm.slack.com/join/shared_invite/zt-1fecwrorm-x5URTlOzBR2fExTU2mWfug#/shared-invite/error) in the [README](https://github.com/firecracker-microvm/firecracker/blob/a9300c13c823e4192a042a2d0c765e0bae5a6319/README.md) does not work anymore because `The link is no longer active`

## To Reproduce
Click on the invite link in the README

## Expected behaviour

Invite link works

## Environment
n.a.

## Additional context
n.a

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by xmarcalx** [comment] 2023-07-25 20:34
Hi @Furisto ,

Thank you very much for reporting this issue and your interest to join our community.
Sorry for the inconvenient, unfortunately seems that Slack rotate links once per year (even if was set to never expire!).

The problem should be fixed by #3989.
If you didn't join yet, please feel free to use the new link and let us know if the problem is resolved for you :)

**Comment by xmarcalx** [comment] 2023-07-26 07:44
Closing this issue, the PR in our codebase has been merged as well the invitation into our website! 
Thanks again for the report! I hope you will enjoy being part of the community soon!

**Closed by xmarcalx** 2023-07-26 07:44 UTC
Labels: Type: Bug, Type: Documentation

**Comment by Furisto** [comment] 2023-07-28 13:26
Hey @xmarcalx thank you for updating the link. I can confirm it works perfectly now!
