### ISSUE TITLE
[Bug] Processes get stuck after resuming VM from snapshot

### ISSUE THREAD

**Issue by bduffany** [firecracker-microvm/firecracker#4099] opened 2023-09-10 19:46 UTC
# Describe the bug

After resuming a VM from snapshot, processes occasionally get stuck. A minimal example is an `init` binary that just runs `while (true) { sleep 100ms ; print 'hello' }` - after resuming from snapshot, it only sometimes is able to resume the loop, and other times it gets stuck and does not print anything at all.

## To Reproduce

1. Clone the following repo, which has the minimal code needed to reproduce: https://github.com/bduffany/firecracker-sleep-issue
2. Make sure you have `make`, `cc` (C compiler, from `gcc` package), `glibc-static` (for statically linking the init binary), and `jq` (for parsing firecracker API output)
3. Run `make test`

`make test` is doing the following:
- Fetches the firecracker v1.4.0 release binary from GitHub as well as vmlinux 4.14 from the https://github.com/firecracker-microvm/firecracker-demo repo
- Runs firecracker with an initrd where the init binary just loops infinitely, printing "running" then sleeping for 100ms. 
- Streams the VM logs to the kernel (using `tail -f` in the background)
- Every 1s, pauses the VM, takes a snapshot, then kills firecracker (SIGTERM), then restarts firecracker, resuming the VM from snapshot.

## Expected behaviour

When running `make test` in that repo, the init binary should print `running` several times after each resume. But on some resumes, it appears stuck, and does not print anything until the next resume.

Interesting details:
- The issue does NOT reproduce if I replace the `nanosleep` syscalls with an NOP loop of 1e9 iterations (`for (int i=0; i<1e9; i++) continue;`)
- The issue seems specific to snapshotting, not just pausing and resuming the VM. I tried just doing pause/resume without taking a snapshot and then restarting the `firecracker` binary in between, but could not reproduce.
- I could not reproduce this on an Intel CPU so far, only AMD (have tried 2 different Intel machines and 2 different AMD machines).

## Environment

- Firecracker v1.4.0
- Host kernel v6.2.0 (Ubuntu 22.04)
  - **UPDATE:** also reproduced on host kernel v5.10 - `m6a.metal` instance
- Guest kernel 4.14.55-84.37.amzn2.x86_64, from https://github.com/firecracker-microvm/firecracker-demo
  - Also tried compiling 5.10 using the recommended guest config - the issue still reproduces.
- Rootfs: none (initrd only)
- Architecture: x86_64 (AMD Ryzen CPU)
  - **UPDATE:** Also reproduced with AMD EPYC (`m6a.metal` instance)
- GLIBC 2.35 (for init binary)

## Additional context

This repro above is a minimal example of a much more troublesome issue where we are having trouble reconnecting to microVMs after resuming them from snapshots. We are running a server inside the VM and are having trouble connecting to over vsock. I suspected that the guest process was "stuck" somehow since when running `sleep 1 && print('hello')` in a background loop, it sometimes doesn't print anything. I came up with this minimal reproducer for this behavior.

## Checks

- Have you searched the Firecracker Issues database for similar problems?
  - https://github.com/firecracker-microvm/firecracker/issues/3020 - not sure if this is related, but it was closed without resolution. The final comment said to re-open if it could be reproduced with a supported kernel version
- Have you read the existing relevant Firecracker documentation?
  - I have read the FAQ about guest clock drift / NTP, but this appears more significant than just clock drift since I think nanosleep should work based on relative timing? I could be wrong, though.
- Are you certain the bug being reported is a Firecracker issue?
  - Not 100% certain, but given that it happens only when loading a snapshot, it seems like it could be Firecracker-related

**Comment by bduffany** [comment] 2023-09-10 20:31
I'm not sure if this helps, but I randomly discovered that the issue can no longer be reproduced if I set the `nolapic` kernel boot param. (I don't really understand exactly what that param does or if there are any downsides, so I'm hesitant to call it a solution yet.)

**Comment by zulinx86** [comment] 2023-09-11 13:47
> Does Firecracker have any test suites that run against AMD machines? I would be happy to contribute a test that demonstrates the issue.

Yes. m6a.metal is AMD instance that firecracker is tested on. Thanks for your help and effort!

**Comment by bduffany** [comment] 2023-09-11 13:48
Ah OK, I will actually just spin one of those up on AWS then :) Thanks

**Comment by bduffany** [comment] 2023-09-11 14:20
I was able to reproduce this on an m6a.metal instance with Linux 5.10.

If it helps, I had to run `sudo yum install make gcc glibc-static jq` in order for the `make test` command in my repro repository to work. I also ran `sudo yum groupinstall "Developer Tools"` but I'm not sure if that part was actually needed.

**Comment by bduffany** [comment] 2023-09-11 14:22
Here is what it looks like when running the repro - whenever it prints "Letting the VM run for a little bit..." I expect to see "init: running..." being printed several times, but it appears to only get printed some of the time:

https://github.com/firecracker-microvm/firecracker/assets/2414826/5f752b5e-e045-4204-b877-3f0476d967a1

**Comment by bduffany** [comment] 2023-09-11 14:55
I've tried codesandbox's fork of firecracker which disables async page faults: https://github.com/codesandbox/firecracker/commit/41643714f571f281ac9777ff72254591856ea0da

I am not sure if this helps, but I was not able to reproduce the issue using codesandbox's firecracker release which has this commit.

**Comment by CuriousGeorgiy** [comment] 2023-09-15 14:11
Not sure this is related, but our implementation of container snapshots backed by firecracker VMs using firecracker-containerd in vHive stumbles upon a similar problem: it seems like firecracker-containerd's in-VM agent stops responding and hangs after a snapshot created and the VM is resumed (vhive-serverless/vhive#818).

**Comment by bduffany** [comment] 2023-09-15 14:51
@CuriousGeorgiy are you hitting this issue on an AMD CPU, or Intel? Also, could you try running the repro steps I posted in the issue description, and letting us know if you see the same problem that I described? This would be very helpful as an extra data point 🙏

**Comment by CuriousGeorgiy** [comment] 2023-09-15 15:11
@bduffany I am renting a node on CloudLab with an Intel CPU. I tried running the repro steps you posted, but after waiting for 100 rounds I didn't see any problems you described.

**Comment by bduffany** [comment] 2023-09-15 19:50
@CuriousGeorgiy thanks for running the repro steps! It is interesting that you couldn't repro the issue on an Intel machine. I think that means its more likely that this issue is AMD-specific.

I think the issue that you are seeing is probably different than the one reported here, since the repro script doesn't produce the issue in your case. I'd recommend reporting a separate issue to the firecracker-containerd repo, ideally with a minimal repro setup.

**Comment by sudanl0** [comment] 2023-09-28 17:14
Hi @bduffany, thanks for providing the repro steps. We are working on this issue and to provide an update :
- I was able to reproduce the issue on an AMD instance
- I modified your steps to run 5 times instead of 100 and saved snapshots from each run. When tried manually to load the snapshots I am able to see the prints which were otherwise not seen through the script. This means the guest takes more time to start in the issue scenario but, the guest is always able to boot if tried manually.
- In some cases I saw that the prints were seen if a sleep of 5 seconds was added instead of 1 but it was random.
We'll continue investigating this and let you know if we have an update.

**Comment by bduffany** [comment] 2023-11-02 00:35
Friendly ping, is this issue still on your radar? This is still a pain point for us when using Firecracker.

**Comment by sudanl0** [comment] 2023-11-06 10:53
Hi @bduffany, we are tracking this as one of our high priority task. We'll let you know as soon as we have an update on this.

**Comment by ShadowCurse** [comment] 2023-11-14 09:55
Hi @bduffany. We are still working on the root cause of this issue. We will update you as soon as possible.

**Comment by pb8o** [comment] 2024-01-23 11:35
Hi @bduffany, I am currently looking at this. I found that passing `lapic=notscdeadline` in the kernel boot command line also seems to fix it, so I think that narrows it down a bit. I will continue investigating, but could you confirm?

**Comment by bduffany** [comment] 2024-02-29 19:39
hey @pb8o, curious whether there are any leads on this that you can share? We would love to be able to run our Firecracker workloads on AMD machines, because they are much cheaper. Happy to help any way that I can - not much of an expert on virtualization but can maybe help try to find a more consistent repro, if that is part of the issue?

**Comment by pb8o** [comment] 2024-03-18 12:00
Hi @bduffany,

Sorry for the delay, unfortunately we were not able to make progress regarding this issue. 
We are still tracking the problem and will provide an update once we will have more data to share.

**Comment by bduffany** [comment] 2024-03-26 21:26
FYI, we started hitting this again, but on Intel, after GCP upgraded our nodes from kernel version `5.15.0-1036-gke` to `5.15.0-1052-gke`. We were seeing similar symptoms this time, but with some RCU stalls in the kernel logs. The same repro script from the PR description also can reproduce the issue on the upgraded nodes. Setting `lapic=notscdeadline` also seems to work in this case as a mitigation, though we don't fully understand the implications yet.

**Comment by bduffany** [comment] 2024-03-26 23:03
While investigating, we came across this kernel patch which seems possibly relevant: https://lore.kernel.org/lkml/ZQCayNY+8PYvfc40@google.com/T/

However we did not get a chance to patch this into our host kernel to see if it works. That commit message says that the issue only exists in kernel v6.3-rc1+ and was introduced by 8e6ed96cdd50, but it's unclear whether that commit exists in the GKE kernel build we were using.

**Comment by ShivanshVij** [comment] 2024-03-27 00:27
Looks like this was merged into the linux kernel (https://github.com/kvm-x86/linux/commit/9cfec6d097c6) but won't get backported by default.

**Comment by pb8o** [comment] 2024-07-02 09:52
Hi @bduffany, first of all thanks for your patience. We are sorry that it is taking so long to root cause and the time between updates, and I wanted to reassure you that we take this issue seriously and we are still investigating a possible solution.

Regarding the patch

> While investigating, we came across this kernel patch which seems possibly relevant: [KVM: x86: Fix lapic timer interrupt lost after loading a snapshot](https://lore.kernel.org/lkml/ZQCayNY+8PYvfc40@google.com/T/)

I was able to reproduce the issue on Ubuntu 24.04, which had a 6.8.0 kernel with that patch. I was also able to reproduce the issue with newer guest kernels and newer AMD CPUs like Genoa, so we can rule out something that is fixed in newer kernels or CPUs.

At this point we believe the issue is that we use TSC deadline feature in both Intel and AMD. Intel does support TSC deadline, so works fine. In the AMD CPUs we tested however, TSC deadline is not enabled but Firecracker still presents it to the guest via `CPUID`. In this case KVM emulates TSC deadline and during a snapshot resume this emulation seems to not work (this is the part we haven't figured out yet if it's Firecracker or KVM who is at fault here).

We have tried working around the issue in #4655 by only enabling TSC deadline if it's enabled on the host. This works fine, but creates a boot time regression of 40-50% in our tests. We are currently trying to understand where this time is going and if we can mitigate it.

**Comment by roypat** [comment] 2024-07-08 06:41
Good morning @bduffany,
Sorry again for taking so long for getting to the bottom of this. We believe to have found the root-cause of this issue and have a proposed fix in #4666. The problem was Firecracker not correctly taking into account dependencies between `MSR_IA32_TSC` and `MSR_IA32_TSC_DEADLINE`, which lead to `MSR_IA32_TSC_DEADLINE` being restored before `MSR_IA32_TSC`. However, since KVM relies on the guest TSC value (and thus `MSR_IA32_TSC`) for restoration of the deadline MSR, this lead to incorrect timer intialization. 

With the commit from #4666, I am no longer able to reproduce the issue. Could you also give this a try? Thanks!

To follow up on some loose ends from @pb8o's last update: The alternate fix of simply disabling the TSC_DEADLINE feature (either via CPUID or `lapic=notscdeadline` kernel boot argument) is equally valid. This forces the kernel to fall back onto the APIC timer's oneshot and period modes to setting up timer interrupts. The only difference is that periodic/one-shot modes of the APIC timer run at a different clock frequency than the TSC_DEADLINE time (which counts at the TSC frequency). Thus, the kernel needs to calibrate on startup to find out how to convert between nanoseconds and APIC timer clock cycles. This calibration takes 100ms (depending on kernel configuration), and is the reason why we were seeing a boottime regression with this option. This calibration cannot be avoided, as there is currently no way for a hypervisor to tell a Linux guest about the APIC timer frequency on AMD (funnily enough, there are CPUID leaves that KVM checks on Intel, but that's exactly the case where we don't have any problems...). Other than this initial calibration, there should be no impact on guest functionality though.

**Closed** 2024-07-08 17:47 UTC
Labels: Type: Bug, Priority: High

**Comment by bduffany** [comment] 2024-07-15 22:31
@roypat Thank you so much for the fix! I verified on my AMD machine that the script is able to complete 100 iterations without getting stuck.
