### ISSUE TITLE
Firecracker unexpectedly crashes even on 'safe' signals

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#197] opened 2018-03-23 20:00 UTC
For example:

Catch the EINTR error when running the epoll loop.
Error:
thread '<unnamed>' panicked at 'VMM thread fail: Poll(Error { repr: Os { code: 4, message: "Interrupted system call" } })', /checkout/src/libcore/result.rs:906:4

I ran into this issue when my laptop went to sleep. I guess the firecracker process got a EINTR signal that we don't handle properly in the epoll loop in run_control.

**Comment by Lay-ton** [comment] 2019-10-29 21:36
Hi, @andreeaflorescu I am a student in UT Austin's virtualization class. We are a group of 3 and were wondering if this was still an open issue. If so could we get a little more information on what needs to be done?

**Comment by andreeaflorescu** [comment] 2019-10-29 22:55
@Lay-ton I would need to check if this is still opened. @alexandruag do you have more context?

In any case I am not super sure that this is a good first issue. Are you interested in a particular type of issue? I could find something else for you.

**Comment by dianpopa** [comment] 2020-03-11 19:49
Duplicate of #1604. Go there for discussions and info on fix.

**Comment by acatangiu** [comment] 2020-03-16 16:52
I've changed the title of this issue to better represent the issue.

There is no need to mask signals, we just need to make sure Firecracker can correctly continue execution after being interrupted by non-terminating signals.

There are some details in duplicate #1604 as well.

**Closed** 2020-03-19 12:32 UTC
Labels: Contribute: Good First Issue, Priority: Low, Quality: Bug
